### ISSUE TITLE
Track route fails if server doesn't require a password

### ISSUE THREAD

**Issue by kevcenteno** [node-freight/freight-server#19] opened 2015-10-16 22:32 UTC
At https://github.com/node-freight/freight-server/blob/master/routes/freight.js#L93, there's a check for `req.body.password`, and this will return `falsy` if `req.body.password` is an empty string.

**Comment by vladikoff** [comment] 2015-11-13 23:49
Closed via https://github.com/node-freight/freight-server/pull/20#issuecomment-156592326 
This is by design. Will reopen if needed

**Closed by vladikoff** 2015-11-13 23:49 UTC

**Comment by kevcenteno** [comment] 2015-11-13 23:52
If the user explicitly sets no password in their config, then we should honour that setting

**Comment by vladikoff** [comment] 2015-11-13 23:55
> If the user explicitly sets no password in their config, then we should honour that setting

Got it, filed https://github.com/node-freight/freight-server/issues/21
I will need to do a few more changes (more than PR 20)
